### ISSUE TITLE
dappchain compiles and runs but fails to listen on linux

### ISSUE THREAD

**Issue by bgits** [loomnetwork/tiles-chain#11]
Following all instructions for the dappchain in the readme except replacing `osx` with `linux` for `wget https://storage.googleapis.com/private.delegatecall.com/loom/osx/build-404/loom` also tried alternative of `curl https://raw.githubusercontent.com/loomnetwork/loom-sdk-documentation/master/scripts/get_loom.sh | sh`

both builds start a running server but do not listen for requests and only displays the following in the console:
```
I[10-11|18:50:27.727] Using simple log event dispatcher
2018-10-11T18:50:27.740Z [DEBUG] plugin: starting plugin: path=/bin/sh args="[sh -c /root/loom_test/tiles-chain/dappchain/build/contracts/tile-chain.0.0.1]"
2018-10-11T18:50:27.740Z [DEBUG] plugin: waiting for RPC address: path=/bin/sh
2018-10-11T18:50:27.750Z [DEBUG] plugin.sh: plugin address: address=/tmp/plugin040960795 network=unix timestamp=2018-10-11T18:50:27.749Z
2018-10-11T18:50:27.750Z [DEBUG] plugin: plugin process exited: path=/bin/sh
```

running on `Ubuntu 16.04.4 LTS`

**Comment by bgits** [comment]
Managed to get the chain run on the default build, on my modified version I get this stack trace:
```
I[10-11|19:54:04.013] Using simple log event dispatcher
panic: plugin not found

goroutine 1 [running]:
github.com/loomnetwork/loomchain.(*Application).InitChain(0xc4202c9800, 0x5bbfaa5c, 0xc4204bb020, 0x7, 0xc42011b5e0, 0xc4202cc6e0, 0x1, 0x1, 0x0, 0x0, ...)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/loomnetwork/loomchain/app.go:229 +0x155
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc4200894a0, 0x5bbfaa5c, 0xc4204bb020, 0x7, 0xc42011b5e0, 0xc4202cc6e0, 0x1, 0x1, 0x0, 0x0, ...)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:199 +0x98
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc4202b73c0, 0x5bbfaa5c, 0xc4204bb020, 0x7, 0xc42011b5e0, 0xc4202cc6e0, 0x1, 0x1, 0x0, 0x0, ...)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:65 +0x59
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc42001adc0, 0xc4204bb020, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/consensus/replay.go:278 +0x108a
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc42001adc0, 0x18fa400, 0xc420843600, 0x4, 0x18ef500)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/consensus/replay.go:246 +0x3e5
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc420843600, 0xc42018b700, 0x15)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/proxy/multi_app_conn.go:108 +0x527
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/libs/common.(*BaseService).Start(0xc420843600, 0x0, 0x0)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/libs/common/service.go:130 +0x3bd
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/node.NewNode(0xc4208b5e60, 0x18f0f40, 0xc420195290, 0x18d61a0, 0xc420d17bc0, 0xc420d2a870, 0x182ac48, 0x182ac50, 0x18ef500, 0xc420d17c20, ...)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/node/node.go:187 +0x693
github.com/loomnetwork/loomchain/abci/backend.(*TendermintBackend).Start(0xc42083f3e0, 0x18f75c0, 0xc4202c9800, 0x18da9c0, 0xc42083f460)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/loomnetwork/loomchain/abci/backend/tendermint.go:265 +0x42b
main.newRunCommand.func1(0xc42017ec80, 0x21aaef8, 0x0, 0x0, 0x0, 0x0)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/loomnetwork/loomchain/cmd/loom/loom.go:302 +0x478
github.com/spf13/cobra.(*Command).execute(0xc42017ec80, 0x21aaef8, 0x0, 0x0, 0xc42017ec80, 0x21aaef8)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/spf13/cobra/command.go:762 +0x468
github.com/spf13/cobra.(*Command).ExecuteC(0x2128220, 0xc42085c780, 0xc42085ca00, 0xc42085cc80)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0x2128220, 0xc42083df08, 0xe)
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/tmp/gopath-jenkins-loom-sdk-pipeline3-478/src/github.com/loomnetwork/loomchain/cmd/loom/loom.go:732 +0x238
```
